package provathreewaymerge;

public class ThreewayConMarco {
	
	CON MARCO PROVO IL THREEWAY MERGE, STO CREANDO UNA MODIFICA SUL NUOVO BRANCH
	
	MODIFICA FATTA DOPO IL PUSH DI MARCO CHE HA MODIFICATO IL MASTER
	
	MODIFICA FATTA DOPO CHE MARCO HA AGGIORNATO IL MASTER. IO MI SCARICO LE SUE MODIFICHE NEL BRANCH MASTER, E POI MI VADO A FARE IL MERGE CON IL BRANCH THREEWAY
	

}
